---
- hosts: all
  become: yes
  vars_files:
    - vars/common.yml
  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "vars/config.yml"
    - name: Add Varnish apt key.
      apt_key:
        url: https://repo.varnish-cache.org/GPG-key.txt
        state: present
    - name: Add Varnish apt repository.
      apt_repository:
        repo: "deb https://repo.varnish-cache.org/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} varnish-{{ varnish_version }}"
        state: present
  roles:
    - geerlingguy.varnish