---
- hosts: all
  become: yes
  vars_files:
    - vars/common.yml
  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "vars/config.yml"
  roles:
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.php-memcached
    - geerlingguy.composer
    - geerlingguy.apache
    - geerlingguy.apache-php-fpm