---
- hosts: all
  become: yes

  vars_files:
    - vars/common.yml
    - vars/php-common.yml
    - vars/httpd-common.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "vars/config.yml"
    - name: Add repository for Apache.
      apt_repository: repo='ppa:ondrej/apache2'

  roles:
    - geerlingguy.apache
    - geerlingguy.apache-php-fpm