---
- hosts: all
  become: yes
  vars_files:
    - vars/common.yml
    - vars/nginx.yml
  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "vars/config.yml"
  roles:
    - geerlingguy.nginx