---
- hosts: all
  become: yes
  vars_files:
    - vars/common.yml
  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "vars/config.yml"
    - name: Add repository for PHP 5.5, 5.6, 7.0 or 7.1.
      apt_repository: repo='ppa:ondrej/php'
      register: php_ondrej_repo
    - name: Add repository for PHP 5 compatibility packages.
      apt_repository: repo='ppa:ondrej/php5-compat'
      when: >
        (php_version == "5.5" or php_version == "5.6")
    - name: Purge PHP version packages.
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
        force: yes
      when: "'php{{ php_version }}' not in item"
      with_flattened:
        - "{{ php_packages|regex_replace('php' + php_version, 'php5.5') }}"
        - "{{ php_packages|regex_replace('php' + php_version, 'php5.6') }}"
        - "{{ php_packages|regex_replace('php' + php_version, 'php7.0') }}"
        - "{{ php_packages|regex_replace('php' + php_version, 'php7.1') }}"
      register: php_purge
    - name: Purge PHP packages installed by default on Ubuntu.
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
        force: yes
      when: php_purge.changed or php_ondrej_repo.changed
      with_items:
        - php-common
    - name: Purge PHP modules directory.
      file:
        path: "{{ item }}"
        state: absent
      when: php_purge.changed
      with_items:
        - "/usr/lib/php5/modules"
        - "/usr/lib/php/modules"
  roles:
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.php-memcached
    - geerlingguy.composer
